import {GroupBox, LineEdit, Button, CheckBox, Slider} from "std-widgets.slint";

export component MainWindow inherits Window {
    in-out property <string> button-text: "Click";
    in-out property <float> slider-value: 0;
    in-out property <string> username: "";
    in-out property <string> password: "";
    in-out property <ColorScheme> color-scheme: dark;
    callback button-clicked(string) -> string;
    title: "Main Window";
    // default-font-family: "WenQuanYi Zen Hei";
    default-font-family: "Noto-Sans";
    width: 600px;
    height: 500px;

    VerticalLayout {
        alignment: start;
        padding-left: 150px;
        padding-right: 150px;

        Rectangle {
            height: 20px;
        }

        Text {
            font-size: 27px;
            font-weight: 700;
            horizontal-alignment: TextHorizontalAlignment.center;
            color: #6f06FF;
            text: "Welcome to Silence";
        }

        VerticalLayout {
        alignment: start;
        padding-left: 50px;
        padding-right: 50px;

            GroupBox {
                title: "Login";

                VerticalLayout {
                    LineEdit {
                        placeholder-text: "username";
                        text <=> root.username;
                    }

                    Rectangle {
                        height: 10px;
                    }

                    LineEdit {
                        input-type: InputType.password;
                        placeholder-text: "password";
                        text <=> root.password;
                    }
                }
            }

            Rectangle {
            height: 10px;
            }

            Button {
                primary: true;
                text: root.button-text;
                clicked => {
                    root.button-text = root.button-clicked(root.username);
                }
            }

            Rectangle {
                height: 20px;
            }

            HorizontalLayout {
                spacing: 10px;
                CheckBox {
                    text: "Remember Login";
                }
            }
        }
    }
}
